baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'joooi.dev'
theme = "hallo"
publishDir = "../portfolio/public"

[Author]
    name = "Yu Joi"

[params]

    greeting = "Hello!"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/joooi13"
    
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/joooi13"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:joinc.dev.info@gmail.com"

    [[params.links]]
        iconset = "fas"
        icon = "book-open"
        title = "note"
        url = "https://note.com/joooi13/"

    [params.colors]
        background = "#dcdcdc"
        foreground = "#edf7ff"
        hover = "#ffba82"

    