[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "anatole/"
    disable = false

[params]
title = "Portfolio"
author = "Yu Joi"
description = "I'm Yu Joi"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/joooi13"
    
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/joooi13"


[[params.socialIcons]]
icon = "fab fa-google-play"
title = "GooglePlay"
url = "https://play.google.com/store/apps/developer?id=JOINC"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"