languageCode = "en"
DefaultContentLanguage = "en"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"
publishDir = "../public"

summarylength = 5
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true

[[related.indices]]
  name = 'keywords'
  weight = 100
  
[[related.indices]]
  name = 'tags'
  weight = 80


[params]
title = "Portfolio"
author = "joooi13.dev"
description = "I'm Yu Joi. Software Engineer."
profilePicture = "images/profile.jpg"
disableThemeSwitcher = true
favicon = "favicons/"
customCss = ["css/custom.css"]
mainSections = ["post"]
enableMediumZoom = false
gtagId = "G-014RE3M7Z8"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/joooi13"
    
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/joooi13"


[[params.socialIcons]]
icon = "fab fa-google-play"
title = "GooglePlay"
url = "https://play.google.com/store/apps/developer?id=JOINC"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:joinc.dev.info@gmail.com"


[menu]


  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Works"
  weight = 300
  identifier = "works"

  [[menu.main]]
  name = "推し時間"
  weight = 310
  identifier = "oshi_countdown"
  url = "/oshi_countdown/"
  parent = "works"  

  [[menu.main]]
  name = "Hi! Hangul"
  weight = 310
  identifier = "hi_hangul"
  url = "/hi_hangul/"
  parent = "works"  

[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 400
  url = "/about/"
