name: hugo-firebase
on:
    push:
      branches:
        - master 
jobs:
    build:
        name: build hugo
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                submodules: true
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: 'latest'
            - name: build hugo pages
              run: ( cd dev && hugo )
    deploy:
        name: deploy to firebase hosting
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: directry check
              run: ls -ltr
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                args: deploy --only hosting
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            - run: echo "🎉 Success!"